// Generated by https://quicktype.io

export interface Brawlers {
  list: Brawler[];
}

export interface Brawler {
  id: number;
  avatarId: number;
  name: string;
  hash: string;
  path: string;
  released: boolean;
  version: number;
  link: string;
  imageUrl: string;
  imageUrl2: string;
  imageUrl3: string;
  class: Class;
  rarity: Rarity;
  unlock: number | null;
  description: string;
  starPowers: Gadget[];
  gadgets: Gadget[];
  videos: Video[];
}

interface Class {
  id: number;
  name: string;
}

interface Gadget {
  id: number;
  name: string;
  path: string;
  version: number;
  description: string;
  imageUrl: string;
  released: boolean;
}

interface Rarity {
  id: number;
  name: string;
  color: string;
}

interface Video {
  type: number;
  name: string;
  description: string;
  duration: string;
  videoUrl: string;
  previewUrl: string;
  uploadDate: string;
}
