// Generated by https://quicktype.io

export interface ClubLog {
  club: Club;
  history: History[];
}

interface Club {
  tag: string;
  name: string;
  trophies: number;
  requiredTrophies: number;
  memberCount: number;
  description: string;
  updated: Updated;
}

interface Updated {
  data: number;
  history: number;
}

interface History {
  type: string;
  data: Data;
  timestamp: number;
}

interface Data {
  joined?: boolean;
  player?: Player;
  type?: string;
  old?: string;
  new?: string;
  promote?: boolean;
}

interface Player {
  tag: string;
  name: string;
}
