// Generated by https://quicktype.io

export interface Events {
  active: Event[];
  upcoming: Event[];
}

export interface Event {
  slot: Slot;
  startTime: string;
  endTime: string;
  reward: number;
  map: Map;
  modifier: Environment | null;
}

export interface Map {
  id: number;
  new: boolean;
  disabled: boolean;
  name: string;
  hash: string;
  version: number;
  link: string;
  imageUrl: string;
  credit: null | string;
  environment: Environment;
  gameMode: GameMode;
  lastActive: number;
  dataUpdated: number;
  stats: Stat[];
  teamStats: TeamStat[];
}

export interface Environment {
  id: number;
  name: string;
  hash: string;
  path?: string;
  version: number;
  imageUrl: string;
}

export interface GameMode {
  id: number;
  name: string;
  hash: string;
  version: number;
  color: string;
  link: string;
  imageUrl: string;
}

export interface Stat {
  brawler: number;
  winRate: number;
  useRate: number;
  starRate?: number;
  avgPosition?: number;
}

export interface TeamStat {
  name: string;
  hash: string;
  brawler1: number;
  brawler2: number;
  brawler3?: number;
  data: Data;
}

export interface Data {
  winRate: number;
  useRate: number;
  wins: number;
  losses: number;
  draws: number;
  total: number;
}

export interface Slot {
  id: number;
  name: string;
  hash: string;
  listAlone: boolean;
  hideable: boolean;
  hideForSlot: number | null;
  background: null | string;
}
