// Generated by https://quicktype.io

export interface Events {
  active: Event[];
  upcoming: Event[];
}

interface Event {
  slot: Slot;
  startTime: string;
  endTime: string;
  reward: number;
  map: Map;
  modifier: null;
}

interface Map {
  id: number;
  new: boolean;
  disabled: boolean;
  name: string;
  hash: string;
  version: number;
  link: string;
  imageUrl: string;
  credit: null | string;
  environment: Environment;
  gameMode: GameMode;
  lastActive: number;
  dataUpdated: number;
  stats: Stat[];
  teamStats: TeamStat[];
}

interface Environment {
  id: number;
  name: string;
  hash: string;
  path: string;
  version: number;
  imageUrl: string;
}

interface GameMode {
  id: number;
  name: string;
  hash: string;
  version: number;
  color: string;
  link: string;
  imageUrl: string;
}

interface Stat {
  brawler: string;
  winRate: number;
  useRate: number;
  starRate?: number;
  avgPosition?: number;
}

interface TeamStat {
  name: string;
  hash: string;
  brawler1: number;
  brawler2: number;
  brawler3?: number;
  data: Data;
}

interface Data {
  winRate: string;
  useRate: string;
  wins: number;
  losses: number;
  draws: number;
  total: number;
}

interface Slot {
  id: number;
  name: string;
  hash: string;
  listAlone: boolean;
  hideable: boolean;
  hideForSlot: number | null;
  background: null | string;
}
