// Generated by https://quicktype.io

export interface GameModes {
  list: GameMode[];
}

export interface GameMode {
  id: number;
  name: string;
  hash: string;
  disabled: boolean;
  color: string;
  version: number;
  title: string;
  tutorial: string;
  description: string;
  shortDescription: string;
  sort1: number;
  sort2: number;
  link: string;
  imageUrl: string;
  imageUrl2: string;
}
