// Generated by https://quicktype.io

export interface Icons {
  player: { [key: string]: PlayerIcon };
  club: { [key: string]: ClubIcon };
}

interface ClubIcon {
  id: number;
  imageUrl: string;
}

interface PlayerIcon {
  id: number;
  imageUrl: string;
  imageUrl2: string;
  brawler: number | null;
}
