// Generated by https://quicktype.io

export interface Icons {
  player: { [key: string]: Player };
  club: { [key: string]: Club };
}

interface Club {
  id: number;
  imageUrl: string;
}

interface Player {
  id: number;
  imageUrl: string;
  imageUrl2: string;
  brawler: number | null;
}
