// Generated by https://quicktype.io

export interface brawlMaps {
  list: brawlMap[];
}

interface brawlMap {
  id: number;
  new: boolean;
  disabled: boolean;
  name: null | string;
  hash: string;
  version: number;
  link: string;
  imageUrl: string;
  credit: null | string;
  environment: Environment;
  gameMode: GameMode;
  lastActive: number | null;
  dataUpdated: number | null;
}

interface Environment {
  id: number;
  name: string;
  hash: string;
  path: string;
  version: number;
  imageUrl: string;
}

interface GameMode {
  id: number;
  name: Name;
  hash: Hash;
  version: number;
  color: Color;
  link: string;
  imageUrl: string;
}

export enum Color {
  Cc33Cc = "#cc33cc",
  Da405C = "#da405c",
  Dc2422 = "#dc2422",
  Dc2423 = "#dc2423",
  E33752 = "#e33752",
  F05031 = "#f05031",
  The10B2B7 = "#10b2b7",
  The27Be47 = "#27be47",
  The339900 = "#339900",
  The387Efc = "#387efc",
  The660066 = "#660066",
  The787878 = "#787878",
  The8Ca0E0 = "#8ca0e0",
}

export enum Hash {
  BigGame = "Big-Game",
  BossFight = "Boss-Fight",
  Bounty = "Bounty",
  BrawlBall = "Brawl-Ball",
  DuoShowdown = "Duo-Showdown",
  GemGrab = "Gem-Grab",
  Heist = "Heist",
  HotZone = "Hot-Zone",
  LoneStar = "Lone-Star",
  PresentPlunder = "Present-Plunder",
  RoboRumble = "Robo-Rumble",
  Showdown = "Showdown",
  Siege = "Siege",
  SuperCityRampage = "Super-City-Rampage",
  Takedown = "Takedown",
  Training = "Training",
}

export enum Name {
  BigGame = "Big Game",
  BossFight = "Boss Fight",
  Bounty = "Bounty",
  BrawlBall = "Brawl Ball",
  DuoShowdown = "Duo Showdown",
  GemGrab = "Gem Grab",
  Heist = "Heist",
  HotZone = "Hot Zone",
  LoneStar = "Lone Star",
  PresentPlunder = "Present Plunder",
  RoboRumble = "Robo Rumble",
  Siege = "Siege",
  SoloShowdown = "Solo Showdown",
  SuperCityRampage = "Super City Rampage",
  Takedown = "Takedown",
  Training = "Training",
}
