// Generated by https://quicktype.io

export interface brawlMaps {
  list: brawlMap[];
}

export interface brawlMap {
  id: number;
  new: boolean;
  disabled: boolean;
  name: string;
  hash: string;
  version: number;
  link: string;
  imageUrl: string;
  credit: null;
  environment: Environment;
  gameMode: GameMode;
  lastActive: number;
  dataUpdated: null;
}

interface Environment {
  id: number;
  name: string;
  hash: string;
  path: string;
  version: number;
  imageUrl: string;
}

interface GameMode {
  id: number;
  name: string;
  hash: string;
  version: number;
  color: string;
  link: string;
  imageUrl: string;
}
